config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :facts
  root to: 'searches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ApplicationRecord
  has_many :search_facts
  has_many :searches, through: :search_facts
end

app/models/search.rb
class Search < ApplicationRecord
  has_many :search_facts
  has_many :facts, through: :search_facts
end

app/models/search_fact.rb
class SearchFact < ApplicationRecord
  belongs_to :search
  belongs_to :fact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :set_fact, only: [:show, :edit, :update, :destroy]

  # GET /facts
  # GET /facts.json
  def index
    @facts = Fact.all
  end

  # GET /facts/1
  # GET /facts/1.json
  def show
  end

  # GET /facts/new
  def new
    @fact = Fact.new
  end

  # GET /facts/1/edit
  def edit
  end

  # POST /facts
  # POST /facts.json
  def create
    @fact = Fact.new(fact_params)

    respond_to do |format|
      if @fact.save
        format.html { redirect_to @fact, notice: 'Fact was successfully created.' }
        format.json { render :show, status: :created, location: @fact }
      else
        format.html { render :new }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facts/1
  # PATCH/PUT /facts/1.json
  def update
    respond_to do |format|
      if @fact.update(fact_params)
        format.html { redirect_to @fact, notice: 'Fact was successfully updated.' }
        format.json { render :show, status: :ok, location: @fact }
      else
        format.html { render :edit }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1
  # DELETE /facts/1.json
  def destroy
    @fact.destroy
    respond_to do |format|
      format.html { redirect_to facts_url, notice: 'Fact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact
      @fact = Fact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fact_params
      params.require(:fact).permit(:ref_id, :value)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # POST /searches
  # POST /searches.json
  def create
    if search_params[:word]
      service = ApiQueryService.new(:word, search_params[:word])
    elsif search_params[:category]
      service = ApiQueryService.new(:category, search_params[:category])
    elsif search_params[:random]
      service = ApiQueryService.new(:random, nil)
    end

    service.execute_query
    @search = service.create_search

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:word, :category, :random)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/facts/_form.html.haml
= form_with(model: fact, local: true) do |form|
  - if fact.errors.any?
    #error_explanation
      %h2
        = pluralize(fact.errors.count, "error")
        prohibited this fact from being saved:
      %ul
        - fact.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :ref_id
    = form.text_field :ref_id
  .field
    = form.label :value
    = form.text_field :value
  .actions
    = form.submit

app/views/facts/edit.html.haml
%h1 Editing Fact
= render 'form', fact: @fact
= link_to 'Show', @fact
|
= link_to 'Back', facts_path

app/views/facts/index.html.haml
%p#notice= notice
%h1 Facts
%table
  %thead
    %tr
      %th Ref
      %th Value
      %th{:colspan => "3"}
  %tbody
    - @facts.each do |fact|
      %tr
        %td= fact.ref_id
        %td= fact.value
        %td= link_to 'Show', fact
        %td= link_to 'Edit', edit_fact_path(fact)
        %td= link_to 'Destroy', fact, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Fact', new_fact_path

app/views/facts/new.html.haml
%h1 New Fact
= render 'form', fact: @fact
= link_to 'Back', facts_path

app/views/facts/show.html.haml
%p#notice= notice
%p
  %strong Ref:
  = @fact.ref_id
%p
  %strong Value:
  = @fact.value
= link_to 'Edit', edit_fact_path(@fact)
|
= link_to 'Back', facts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InspiringBenefitsChallenge
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/searches/_form.html.haml
= form_with(model: search, local: true) do |form|
  - if search.errors.any?
    #error_explanation
      %h2
        = pluralize(search.errors.count, "error")
        prohibited this search from being saved:
      %ul
        - search.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :word
    = form.text_field :word
  .field
    = form.label :category
    = form.text_field :category
  .actions

    = form.submit class: 'btn btn-success'

app/views/searches/edit.html.haml
%h1 Editing Search
= render 'form', search: @search
= link_to 'Show', @search
|
= link_to 'Back', searches_path

app/views/searches/index.html.haml
%p#notice= notice
.text-center
  = image_tag('chuck.png', class: "img-responsive")
  .row
    .col-sm-6
      = link_to 'Search a fact', new_search_path, { :class=>"btn btn-lg btn-success" }
    .col-sm-6
      = link_to 'Random fact', searches_path(search: {random: true}), { :class=>"btn btn-lg btn-danger", method: :post}

%hr

.col-sm-10.offset-sm-1
  .text-center
    %h1 Searches
  %table.table.table-striped
    %thead.thead-dark
      %tr
        %th Type
        %th Value
        %th{:colspan => "2"}
    %tbody
      - @searches.each do |search|
        %tr
          %td= search.search_type
          %td= search.value
          %td= link_to 'Show', search
          %td= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' }
  %br/

app/views/searches/new.html.haml
%h1 New Search
= render 'form', search: @search
= link_to 'Back', searches_path, { :class=>"btn btn-primary" }

app/views/searches/show.html.haml
%p#notice= notice

%p

  %strong Chuch Norris facts by:
  = @search.search_type
  search
  = @search.value

- @search.facts.each do |fact|
  .col-sm-8
    .card.border-info
    .card-body.text-info
      %h5.card-title Chuck Norris says:
      .card-text
        = fact.value



= link_to 'Back', searches_path, { :class=>"btn btn-primary" }